### ISSUE TITLE
Context Big Node in Group Nodes Manager: Missing inputs in visibility toggler

### ISSUE THREAD

**Issue by Battleshack** [rgthree/rgthree-comfy#179] opened 2024-03-26 21:33 UTC
Love your work!

When merging the _Context Big_ node with other nodes, I am unable to hide some inputs.

These Inputs can be hidden:
![bilde](https://github.com/rgthree/rgthree-comfy/assets/112418655/a42c31a7-5c30-4c81-82c8-ec82d7e75e70)

These Inputs can not be hidden:
![bilde](https://github.com/rgthree/rgthree-comfy/assets/112418655/3b88384c-2e02-43d2-8429-5b25e3a42b23)

All outputs can be hidden:
![bilde](https://github.com/rgthree/rgthree-comfy/assets/112418655/ce41c5ae-d198-4f83-a35e-b20332717b37)

**Comment by Battleshack** [comment] 2024-03-27 00:53
Probably related to how ComfyUI handles ` "forceInput": True`

**Comment by rgthree** [comment] 2024-03-27 00:57
I don't really use Group Nodes, but I'm also not incredibly surprised.

So this looks like this is a bug for comfyanonymous and not something I can fix in the Context nodes. Unfortunately, every time I file a bug or even make a PR it is ignored. 

If you'd like to [file over there](https://github.com/comfyanonymous/ComfyUI/issues
), the issue is that their Group Node manager doesn't recognize inputs defines with the `forceInput` option. (ComfyUI originally assumed INTs, STRINGs, etc. will always be a widget, but later added a `forceInput` option so nodes can force these to be inputs from the start; Unfortunately, it looks like the Group Node manager appears to ignore that in these views and assumes they are widgets, as they appear in the Widgets tab).

If you file, let me know. I'll +1 it.

**Comment by rgthree** [comment] 2024-03-27 00:58
_Changing to closed as unplanned, not completed._

**Comment by rgthree** [comment] 2024-03-27 00:58
Changing to closed as unplanned, not completed.

**Comment by rgthree** [comment] 2024-03-27 00:59
_Changing to closed as unplanned, not completed._

**Comment by rgthree** [comment] 2024-03-27 00:59
_Changing to closed as unplanned, not completed._

**Closed by rgthree** 2024-03-27 00:59 UTC
Labels: comfyui_issue

**Comment by Battleshack** [comment] 2024-03-27 01:21
Thanks! I've filed an issue over there. Feel free to +1 it. 

https://github.com/comfyanonymous/ComfyUI/issues/3150#issue-2209627344

**Comment by Robonau** [comment] 2024-09-14 01:20
a jank solution for the not being able to hide the forceInput widgets in group nodes is to have an extension do it
```js
app.registerExtension({
    name: "group_node_forceInput_fix",
    async beforeRegisterNodeDef(_, nodeData, _) {
        // group nodes dont have a description property in the nodeData
        if (!("description" in nodeData)) {
            const Symbol_data = nodeData[Object.getOwnPropertySymbols(nodeData)[0]]
            Object.entries(Symbol_data.nodeData.config).forEach(([key,config]) => {
                Object.entries(config?.input).forEach(([inputKey, input]) => {
                    if (!input.visible) {
                        delete nodeData.input.required[Symbol_data.oldToNewWidgetMap[key][inputKey]]
                    }
                })
            });
        }
    }
})
```

this doesn't put the check boxes in the correct place but it lets you actually hide them if you do unchecked them

this is probably not optimal but is good enough for me, you(rgthree) could add this (or an altered version) to rgthree-comfy since context seems to be one of the biggest reasons for this to be an issue
