### ISSUE TITLE
Seed gets set to "-1" if I queue multiple generations

### ISSUE THREAD

**Issue by JPS-GER** [rgthree/rgthree-comfy#169] opened 2024-03-03 22:14 UTC
If I wait until the previous generation is finished the random seed works fine, but if I press "Queue Prompt" multiple times or use "Batch Count" the seed value get's stuck at "-1" sometimes (don't know the exact conditions) instead of creating a new seed, resulting in very fast generations of the same image from cache, as the seed is "-1" for all those images.

![image](https://github.com/rgthree/rgthree-comfy/assets/142158778/8b576cc5-dbef-4a57-8b2d-edc7fea00aaa)

**Comment by JPS-GER** [comment] 2024-03-03 22:20
You can even trigger it with a very simple workflow like that, if you hammer the "Queue Prompt" button a few times after setting the "Batch Count" to a high number (to make sure it isn't finished before you press the button again):
![image](https://github.com/rgthree/rgthree-comfy/assets/142158778/88449dd5-c238-4d50-84ef-ffbebd7622f4)

**Comment by buzzjeux** [comment] 2024-03-26 16:09
Same problem for me, queue multiple time reset the -1 value to a fixed seed..

**Comment by drumicube** [comment] 2024-03-30 20:48
Same problem for me.
It appeared this week for me, I never had this problem before.

**Comment by rgthree** [comment] 2024-03-31 19:13
_I'm assuming everyone here also has cg-use-anywhere installed (even if not used in the workflow?_

I couldn't reproduce the "-1" sticking, but could reproduce a "real" seed sticking. I've rewrote the seed and changed some of the timing to better handle the changing from a seed back and forth. Please try now and let me know if this has fixed it!

**Comment by rgthree** [comment] 2024-03-31 20:49
I've tested with @JPS-GER's workflow from above (500x at only seed & console nodes) and get 500 random seeds. Going to close this. Let me know if you're still seeing anything odd (for instance, it could very well happen from an another extension that I don't have).

**Closed by rgthree** 2024-03-31 20:49 UTC

**Comment by CHollman82** [comment] 2024-07-03 14:55
I still have this problem. When set to -1 it will mysteriously get stuck on a fixed seed... all the time. It doesn't take more than a few generations for this to happen. When using "Auto-Queue" I get a handful of unique images and then the same image over and over again.
