### ISSUE TITLE
error

### ISSUE THREAD

**Issue by T8star1984** [rgthree/rgthree-comfy#203] opened 2024-04-19 18:20 UTC
![QQ图片20240420022017](https://github.com/rgthree/rgthree-comfy/assets/161950228/edd59b1d-5ada-47a4-ae9d-51dcbc22f85b)

**Comment by rgthree** [comment] 2024-04-20 03:30
I believe this is a duplicate of #202

**Closed by rgthree** 2024-04-20 03:30 UTC
